---
- hosts: controllers
  user: "{{ user }}"
  roles:
    - common
    - rpi_leds
    - docker
    - microk8s
- hosts: workers
  user: "{{ user }}"
  roles:
    - common
    - rpi_leds
    - docker
    - microk8s

