- name: adjust cmdline.txt for microk8s
  become: yes
  replace:
      path: /boot/firmware/cmdline.txt
      regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
      replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
    - "swapaccount=1"

- name: 'install microk8s'
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes

- name: 'set limited containerd logging'
  become: yes
  lineinfile:
    path: /var/snap/microk8s/current/args/containerd
    line: '--log-level fatal'

- name: 'add user to microk8s group'
  become: yes
  command: 'usermod -a -G microk8s {{ user }}'
