---
- name: 'install microk8s'
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes

- name: 'set limited containerd logging'
  become: yes
  lineinfile:
    path: /var/snap/microk8s/current/args/containerd
    line: '--log-level fatal'

- name: 'increase frequency of log rotation'
  become: yes
  template:
    src: logrotate.conf.j2
    dest: '/etc/logrotate.conf'
    backup: yes
    mode: 'u=rw,go=r'
    owner: "root"
    group: "root"

