---
- name: 'ensure subdirectory exists'
  file:
    path: kubernetes/django
    state: directory

- name: 'copy files'
  copy:
    src: ./
    dest: kubernetes/django

- name: 'kubectl apply'
  command: kubectl apply -f {{ item }}
  with_items:
     - kubernetes/django/job-migration.yaml
     - kubernetes/django/deployment.yaml
     - kubernetes/django/service.yaml