- stat: path= /home/{{ user }}/.pyenv
  register: p

- name: 'install pyenv'
  become: yes
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /home/{{ user }}/.pyenv
  when: p.stat.exists == False

- name: 'set permissions of pyenv'
  become: yes
  file:
    path: '/home/{{ user }}/.pyenv'
    mode: 'go-w'
    recurse: yes
    owner: "{{ user }}"
    group: "{{ user }}"




