---
- name: 'Install docker packages'
  become: yes
  apt:
    pkg:
      - docker.io
      - docker-compose

- name: 'Make sure a docker is running'
  become: yes
  systemd:
    state: started
    name: docker
    enabled: yes

- name: 'Write docker daemon config'
  become: yes
  template:
    src: docker_daemon.json.j2
    dest: '/etc/docker/daemon.json'
    backup: yes
    mode: 'u=rw,go=r'
    owner: "root"
    group: "root"
